apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: floatingips.galaxy.k8s.io
spec:
  group: galaxy.k8s.io
  version: v1alpha1
  names:
    kind: FloatingIP
    plural: floatingips
    shortNames:
    - fip
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pools.galaxy.k8s.io
spec:
  group: galaxy.k8s.io
  version: v1alpha1
  names:
    kind: Pool
    plural: pools
  scope: Namespaced